#!/usr/bin/env php
<?php

/**
 * Подключение autoload и ядра фреймворка Yii2.
 */
require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

/**
 * Подключение конфигурации консольного приложения.
 */
$config = require(__DIR__ . '/config/console.php');

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
