#!/usr/bin/env php
<?php

/**
 * Connect autoload and core of Yii2
 *
 */
require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

/**
 * Connect configuration settings
 *
 */
$config = require(__DIR__ . '/config/console.php');

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
